### ISSUE TITLE
Identify in database which permissions are "dangerous"

### ISSUE THREAD

**Issue by megdeb** [covid19-apptracker/covid19-apptracker#131]

**Comment by JDBnhs** [comment]
@carmayna I know it's a little late but could we have a variable for the total number of dangerous permissions for each app? That way we don't have to run code on the frontend to calculate the total and potentially adding more time to apps being loaded.

**Comment by carmayna** [comment]
@JDBnhs , that's really easy to do.

@zach-anderson @megdeb @JDBnhs   do you want to update the model to include that?
