### ISSUE TITLE
Create language in About page linking to repo and mention open source license

### ISSUE THREAD

**Issue by megdeb** [covid19-apptracker/covid19-apptracker#142]
@megdeb  create content
@JDBnhs  update site

**Comment by JDBnhs** [comment]
Hey @megdeb I've gone ahead and added some new language to the About page. Nothing too big but here is what I added on the drive: https://docs.google.com/document/d/1AKYEcVENzPfoy_f8qPRZgaur41an6Y4BLyz8BgyAjlc/edit

Let me know if you want to add more specific language.

**Comment by megdeb** [comment]
@JDBnhs i updated the readme. can you take text from there?
