### ISSUE TITLE
Create prototypes of design for the detailed app page and dangerous permissions

### ISSUE THREAD

**Issue by megdeb** [covid19-apptracker/covid19-apptracker#149]
Ideally this would be something to review before the meeting to discuss the data model change

@JDBnhs checkout exodus-privacy project
https://reports.exodus-privacy.eu.org/en/

**Comment by JDBnhs** [comment]
Here is the mockup for the dangerous permissions. I think keeping it as simple as possible is the best option right now and as we develop the "scoring" guide we can add more complexity. 
https://www.figma.com/proto/43R5coYJakUB0MFyyeTAeF/COVID19-App-Tracker?node-id=115%3A2&viewport=-941%2C-5078%2C0.7793903946876526&scaling=min-zoom

**Comment by megdeb** [comment]
This is complete.
