### ISSUE TITLE
Clearly illustrate if an app is no longer available.

### ISSUE THREAD

**Issue by megdeb** [covid19-apptracker/covid19-apptracker#169]
_User story_
As a member of the public, I would like to quickly understand if an app is no longer available on the Google Play Store. 

_Impact_
Users will immediately be able to observe whether or not something is available or unavailable.

_Background_
Describe the pertinent information related to the feature, bug, story, etc.

_Acceptance Criteria_
- [x] Prototype UI
- [x] Reviewer
- [ ] Implementation of Agreed Upon UI 

_Engineering Notes_
May need different UI indicator not available on main page vs detailed app page.

**Comment by megdeb** [comment]
**What should I include in a story?**

 _User story_
As a [type of user], I would like to [achieve what goal].

_Impact_
Users will immediately be able to observe whether or not something is available or unavailable.

_Background_
Describe the pertinent information related to the feature, bug, story, etc.

_Acceptance Criteria_

- [ ] Prototype UI
- [ ] Implementation of Agreed Upon UI 

_Engineering Notes_
Include engineering or other technical notes that would be helpful for the task at hand.

**Comment by JDBnhs** [comment]
![removed-application_option01](https://user-images.githubusercontent.com/27911156/97093056-e5b9cb80-15fd-11eb-9912-0ee36600ba06.jpg)

**Comment by JDBnhs** [comment]
![removed-application_option02](https://user-images.githubusercontent.com/27911156/97093059-ee120680-15fd-11eb-96d1-9a96ba19da8e.jpg)

**Comment by megdeb** [comment]
Personally, I think it may be better to not add an additional color. Can we go with the orange color with white text that is already on the page? @JDBnhs

**Comment by JDBnhs** [comment]
This is live!
