### ISSUE TITLE
Display a link to the privacy policy on detailed app page

### ISSUE THREAD

**Issue by megdeb** [covid19-apptracker/covid19-apptracker#175]
_Acceptance Criteria_
- [x] Prototype shared with team
- [ ] Implemented

_Engineering Notes_
- Raw data has privacy policy link.
- Duke University asked for the URL in the raw data which @carmayna added last sprint.

**Comment by JDBnhs** [comment]
![image](https://user-images.githubusercontent.com/27911156/97094007-9ecfd400-1605-11eb-9096-10f39d0ef34f.png)

**Comment by JDBnhs** [comment]
![image](https://user-images.githubusercontent.com/27911156/97094008-a2635b00-1605-11eb-982d-2f690a16854c.png)

**Comment by JDBnhs** [comment]
@megdeb I've also gone ahead and added the link to the developer's site because I noticed we weren't doing that before.

**Comment by JDBnhs** [comment]
This is live!
