### ISSUE TITLE
Add new apps submitted to the project

### ISSUE THREAD

**Issue by megdeb** [covid19-apptracker/covid19-apptracker#179]
- [x] Respond to emails (@megdeb) 
- [x] Add https://play.google.com/store/apps/details?id=hk.gov.ogcio.leavehomesafe (@carmayna) 
- [x] Add https://play.google.com/store/apps/details?id=gov.michigan.MiCovidExposure (@carmayna)
- [x] CO Exposure Notifications 
https://play.google.com/store/apps/details?id=gov.co.cdphe.exposurenotifications

- [x] CombatCOVID MDC
https://play.google.com/store/apps/details?id=com.shield.CombatCovidMD

- [x] COVID Alert CT
https://play.google.com/store/apps/details?id=gov.ct.covid19.exposurenotifications

- [x] MD COVID Alert
https://play.google.com/store/apps/details?id=gov.md.covid19.exposurenotifications

- [x] DC Can
https://play.google.com/store/apps/details?id=gov.dc.covid19.exposurenotifications

**Comment by carmayna** [comment]
Completed
